spring.application.name=article-platform

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/article_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.maximum-pool-size=30

# JPA
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.secret=my-secret-key-123456
